# Generated by Django 3.2.20 on 2023-10-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0004_ssoconfigurationorm_ssoproviderorm'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorm',
            name='is_supper_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ssoconfigurationorm',
            name='sso_provider_options',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
