# Generated by Django 3.2.20 on 2023-10-26 02:34

from django.db import migrations, models
import locker_server.api_orm.models.enterprises.enterprises


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0006_enterpriseorm_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseorm',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to=locker_server.api_orm.models.enterprises.enterprises.image_upload_path),
        ),
    ]
