# Generated by Django 3.2.20 on 2023-10-27 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0007_alter_enterpriseorm_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupCredentialORM',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('master_password', models.CharField(max_length=300, null=True)),
                ('master_password_hint', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('key', models.TextField(null=True)),
                ('public_key', models.TextField(null=True)),
                ('private_key', models.TextField(null=True)),
                ('creation_date', models.FloatField()),
                ('kdf', models.IntegerField(default=0)),
                ('kdf_iterations', models.IntegerField(default=100000)),
                ('fd_credential_id', models.CharField(max_length=255, null=True)),
                ('fd_random', models.CharField(max_length=128, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_backup_credentials', to=settings.LS_USER_MODEL)),
            ],
            options={
                'db_table': 'cs_backup_credentials',
                'abstract': False,
                'swappable': 'LS_BACKUP_CREDENTIAL_MODEL',
            },
        ),
    ]
