# Generated by Django 3.2.22 on 2023-11-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0008_backupcredentialorm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseorm',
            name='avatar',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
