# Generated by Django 3.2.22 on 2023-11-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0009_alter_enterpriseorm_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseorm',
            name='checksum',
            field=models.TextField(default=None, null=True),
        ),
    ]
