# Generated by Django 3.2.22 on 2023-11-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0012_backupcredentialorm_security_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupcredentialorm',
            name='security_keys',
        ),
        migrations.AddField(
            model_name='backupcredentialorm',
            name='last_use_date',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='backupcredentialorm',
            name='name',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
