AFFILIATE_SUBMISSION_STATUS_SUBMITTED = "submitted"
AFFILIATE_SUBMISSION_STATUS_REPLIED = "replied"
AFFILIATE_SUBMISSION_STATUS_PROCESSING = "processing"
AFFILIATE_SUBMISSION_STATUS_CANCELED = "canceled"
AFFILIATE_SUBMISSION_STATUS_FINISHED = "finished"

LIST_AFFILIATE_SUBMISSION_STATUS = [
    AFFILIATE_SUBMISSION_STATUS_SUBMITTED, AFFILIATE_SUBMISSION_STATUS_REPLIED,
    AFFILIATE_SUBMISSION_STATUS_PROCESSING, AFFILIATE_SUBMISSION_STATUS_CANCELED,
    AFFILIATE_SUBMISSION_STATUS_FINISHED
]
