KDF_TYPE = {
    0: 'PBKDF2_SHA256'
}


CIPHER_TYPE_LOGIN = 1
CIPHER_TYPE_NOTE = 2
CIPHER_TYPE_CARD = 3
CIPHER_TYPE_IDENTITY = 4
CIPHER_TYPE_TOTP = 5
CIPHER_TYPE_CRYPTO_ACCOUNT = 6
CIPHER_TYPE_CRYPTO_WALLET = 7
CIPHER_TYPE_MASTER_PASSWORD = 8
# Sub cipher types
CIPHER_TYPE_DRIVER_LICENSE = 9
CIPHER_TYPE_CITIZEN_ID = 10
CIPHER_TYPE_PASSPORT = 11
CIPHER_TYPE_SOCIAL_SECURITY_NUMBER = 12
CIPHER_TYPE_WIRELESS_ROUTER = 13
CIPHER_TYPE_SERVER = 14
CIPHER_TYPE_API = 15
CIPHER_TYPE_DATABASE = 16


MAP_CIPHER_TYPE_STR = {
    CIPHER_TYPE_LOGIN: "password",
    CIPHER_TYPE_NOTE: "note",
    CIPHER_TYPE_CARD: "card",
    CIPHER_TYPE_IDENTITY: "identity",
    CIPHER_TYPE_TOTP: "totp",
    CIPHER_TYPE_CRYPTO_ACCOUNT: "crypto account",
    CIPHER_TYPE_CRYPTO_WALLET: "crypto wallet",
    CIPHER_TYPE_DRIVER_LICENSE: "driver license",
    CIPHER_TYPE_CITIZEN_ID: "citizen id",
    CIPHER_TYPE_PASSPORT: "passport",
    CIPHER_TYPE_SOCIAL_SECURITY_NUMBER: "social secure number",
    CIPHER_TYPE_WIRELESS_ROUTER: "wireless router",
    CIPHER_TYPE_SERVER: "server",
    CIPHER_TYPE_API: "api",
    CIPHER_TYPE_DATABASE: "database"
}

LIST_CIPHER_TYPE = [
    CIPHER_TYPE_LOGIN, CIPHER_TYPE_NOTE, CIPHER_TYPE_CARD, CIPHER_TYPE_IDENTITY, CIPHER_TYPE_TOTP,
    CIPHER_TYPE_CRYPTO_ACCOUNT, CIPHER_TYPE_CRYPTO_WALLET, CIPHER_TYPE_MASTER_PASSWORD,
    CIPHER_TYPE_DRIVER_LICENSE, CIPHER_TYPE_CITIZEN_ID, CIPHER_TYPE_PASSPORT,
    CIPHER_TYPE_SOCIAL_SECURITY_NUMBER, CIPHER_TYPE_WIRELESS_ROUTER, CIPHER_TYPE_SERVER, CIPHER_TYPE_API,
    CIPHER_TYPE_DATABASE
]

IMMUTABLE_CIPHER_TYPES = [
    CIPHER_TYPE_MASTER_PASSWORD
]

# Duration to sync data when update on multiple device
SYNC_DURATION_EXPIRED = 1           # 1 second


# List custom field types
CUSTOM_FIELD_TYPE_TEXT = 0
CUSTOM_FIELD_TYPE_HIDDEN = 1
CUSTOM_FIELD_TYPE_BOOLEAN = 2       # Ignore
CUSTOM_FIELD_TYPE_LINKED = 3        # Ignore
CUSTOM_FIELD_TYPE_URL = 4
CUSTOM_FIELD_TYPE_EMAIL = 5
CUSTOM_FIELD_TYPE_ADDRESS = 6
CUSTOM_FIELD_TYPE_DATE = 7
CUSTOM_FIELD_TYPE_MONTH_YEAR = 8
CUSTOM_FIELD_TYPE_PHONE = 9

LIST_CUSTOM_FIELD_TYPE = [
    CUSTOM_FIELD_TYPE_TEXT, CUSTOM_FIELD_TYPE_HIDDEN, CUSTOM_FIELD_TYPE_BOOLEAN, CUSTOM_FIELD_TYPE_LINKED,
    CUSTOM_FIELD_TYPE_URL, CUSTOM_FIELD_TYPE_EMAIL, CUSTOM_FIELD_TYPE_ADDRESS,
    CUSTOM_FIELD_TYPE_DATE, CUSTOM_FIELD_TYPE_MONTH_YEAR, CUSTOM_FIELD_TYPE_PHONE
]
