FA2_METHOD_SMART_OTP = "smart_otp"
FA2_METHOD_MAIL_OTP = "mail"

LIST_FA2_METHOD = [FA2_METHOD_SMART_OTP, FA2_METHOD_MAIL_OTP]

FA2_EXPIRED_TIME = 30  # Base days
FA2_MAIL_CODE_EXPIRED_TIME = 10  # Base minute
