SSO_PROVIDER_OAUTH2 = "oauth2"

OAUTH2_BEHAVIOR_GET = "redirect_get"
OAUTH2_BEHAVIOR_POST = "form_post"

LIST_VALID_SSO_PROVIDERS = [
    SSO_PROVIDER_OAUTH2
]
LIST_OAUTH2_BEHAVIOR = [OAUTH2_BEHAVIOR_GET, OAUTH2_BEHAVIOR_POST]
