KDF_TYPE = {
    0: 'PBKDF2_SHA256'
}


CIPHER_TYPE_LOGIN = 1
CIPHER_TYPE_NOTE = 2
CIPHER_TYPE_CARD = 3
CIPHER_TYPE_IDENTITY = 4
CIPHER_TYPE_TOTP = 5
CIPHER_TYPE_CRYPTO_ACCOUNT = 6
CIPHER_TYPE_CRYPTO_WALLET = 7
CIPHER_TYPE_MASTER_PASSWORD = 8

LIST_CIPHER_TYPE = [
    CIPHER_TYPE_LOGIN, CIPHER_TYPE_NOTE, CIPHER_TYPE_CARD, CIPHER_TYPE_IDENTITY, CIPHER_TYPE_TOTP,
    CIPHER_TYPE_CRYPTO_ACCOUNT, CIPHER_TYPE_CRYPTO_WALLET, CIPHER_TYPE_MASTER_PASSWORD
]

# Duration to sync data when update on multiple device
SYNC_DURATION_EXPIRED = 1           # 1 second


# List custom field types
CUSTOM_FIELD_TYPE_TEXT = 0
CUSTOM_FIELD_TYPE_HIDDEN = 1
CUSTOM_FIELD_TYPE_BOOLEAN = 2       # Ignore
CUSTOM_FIELD_TYPE_LINKED = 3        # Ignore
CUSTOM_FIELD_TYPE_URL = 4
CUSTOM_FIELD_TYPE_EMAIL = 5
CUSTOM_FIELD_TYPE_ADDRESS = 6
CUSTOM_FIELD_TYPE_DATE = 7
CUSTOM_FIELD_TYPE_MONTH_YEAR = 8
CUSTOM_FIELD_TYPE_PHONE = 9

LIST_CUSTOM_FIELD_TYPE = [
    CUSTOM_FIELD_TYPE_TEXT, CUSTOM_FIELD_TYPE_HIDDEN, CUSTOM_FIELD_TYPE_BOOLEAN, CUSTOM_FIELD_TYPE_LINKED,
    CUSTOM_FIELD_TYPE_URL, CUSTOM_FIELD_TYPE_EMAIL, CUSTOM_FIELD_TYPE_ADDRESS,
    CUSTOM_FIELD_TYPE_DATE, CUSTOM_FIELD_TYPE_MONTH_YEAR, CUSTOM_FIELD_TYPE_PHONE
]
