KDF_TYPE = {
    0: 'PBKDF2_SHA256'
}


CIPHER_TYPE_LOGIN = 1
CIPHER_TYPE_NOTE = 2
CIPHER_TYPE_CARD = 3
CIPHER_TYPE_IDENTITY = 4
CIPHER_TYPE_TOTP = 5
CIPHER_TYPE_CRYPTO = 6

LIST_CIPHER_TYPE = [
    CIPHER_TYPE_LOGIN, CIPHER_TYPE_NOTE, CIPHER_TYPE_CARD, CIPHER_TYPE_IDENTITY, CIPHER_TYPE_TOTP, CIPHER_TYPE_CRYPTO
]

# Duration to sync data when update on multiple device
SYNC_DURATION_EXPIRED = 1           # 1 second
