KDF_TYPE = {
    0: 'PBKDF2_SHA256'
}


CIPHER_TYPE_LOGIN = 1
CIPHER_TYPE_NOTE = 2
CIPHER_TYPE_CARD = 3
CIPHER_TYPE_IDENTITY = 4
CIPHER_TYPE_TOTP = 5
CIPHER_TYPE_CRYPTO_ACCOUNT = 6
CIPHER_TYPE_CRYPTO_WALLET = 7

LIST_CIPHER_TYPE = [
    CIPHER_TYPE_LOGIN, CIPHER_TYPE_NOTE, CIPHER_TYPE_CARD, CIPHER_TYPE_IDENTITY, CIPHER_TYPE_TOTP,
    CIPHER_TYPE_CRYPTO_ACCOUNT, CIPHER_TYPE_CRYPTO_WALLET
]

# Duration to sync data when update on multiple device
SYNC_DURATION_EXPIRED = 1           # 1 second


# List custom field types
CUSTOM_FIELD_TYPE_TEXT = 0
CUSTOM_FIELD_TYPE_HIDDEN = 1
CUSTOM_FIELD_TYPE_BOOLEAN = 2
CUSTOM_FIELD_TYPE_LINKED = 3

LIST_CUSTOM_FIELD_TYPE = [
    CUSTOM_FIELD_TYPE_TEXT, CUSTOM_FIELD_TYPE_HIDDEN, CUSTOM_FIELD_TYPE_BOOLEAN, CUSTOM_FIELD_TYPE_LINKED
]
