CLIENT_ID_WEB = "web"
CLIENT_ID_BROWSER = "browser"
CLIENT_ID_MOBILE = "mobile"
CLIENT_ID_DESKTOP = "desktop"
CLIENT_ID_CLI = "cli"
LIST_CLIENT_ID = [CLIENT_ID_WEB, CLIENT_ID_BROWSER, CLIENT_ID_MOBILE, CLIENT_ID_DESKTOP]

DEVICE_TYPE_ANDROID = 0
DEVICE_TYPE_IOS = 1
DEVICE_TYPE_EXTENSION_CHROME = 2
DEVICE_TYPE_EXTENSION_FIREFOX = 3
DEVICE_TYPE_EXTENSION_OPERA = 4
DEVICE_TYPE_EXTENSION_EDGE = 5
DEVICE_TYPE_WINDOWS = 6
DEVICE_TYPE_MAC = 7
DEVICE_TYPE_LINUX = 8
DEVICE_TYPE_BROWSER_CHROME = 9
DEVICE_TYPE_BROWSER_FIREFOX = 10
DEVICE_TYPE_BROWSER_OPERA = 11
DEVICE_TYPE_BROWSER_EDGE = 12
DEVICE_TYPE_BROWSER_IE = 13
DEVICE_TYPE_BROWSER_UNKNOWN = 14
DEVICE_TYPE_AMAZON_ANDROID = 15
DEVICE_TYPE_UWP = 16
DEVICE_TYPE_BROWSER_SAFARI = 17
DEVICE_TYPE_BROWSER_VIVALDI = 18
DEVICE_TYPE_EXTENSION_VIVALDI = 19
DEVICE_TYPE_EXTENSION_SAFARI = 20
DEVICE_TYPE_EXTENSION_BRAVE = 21

LIST_DEVICE_TYPE = [
    DEVICE_TYPE_ANDROID, DEVICE_TYPE_IOS,
    DEVICE_TYPE_EXTENSION_CHROME, DEVICE_TYPE_EXTENSION_FIREFOX, DEVICE_TYPE_EXTENSION_OPERA,
    DEVICE_TYPE_EXTENSION_EDGE,
    DEVICE_TYPE_WINDOWS, DEVICE_TYPE_MAC, DEVICE_TYPE_LINUX,
    DEVICE_TYPE_BROWSER_CHROME, DEVICE_TYPE_BROWSER_FIREFOX, DEVICE_TYPE_BROWSER_OPERA,
    DEVICE_TYPE_BROWSER_EDGE, DEVICE_TYPE_BROWSER_IE, DEVICE_TYPE_BROWSER_UNKNOWN,
    DEVICE_TYPE_AMAZON_ANDROID,
    DEVICE_TYPE_UWP,
    DEVICE_TYPE_BROWSER_SAFARI, DEVICE_TYPE_BROWSER_VIVALDI,
    DEVICE_TYPE_EXTENSION_VIVALDI, DEVICE_TYPE_EXTENSION_SAFARI, DEVICE_TYPE_EXTENSION_BRAVE
]
