# ------------------- Emergency Access Type --------------------- #
EMERGENCY_ACCESS_STATUS_INVITED = "invited"
EMERGENCY_ACCESS_STATUS_ACCEPTED = "accepted"
EMERGENCY_ACCESS_STATUS_CONFIRMED = "confirmed"
EMERGENCY_ACCESS_STATUS_RECOVERY_INITIATED = "recovery_initiated"
EMERGENCY_ACCESS_STATUS_RECOVERY_APPROVED = "recovery_approved"


MAP_EMERGENCY_STATUS = {
    0: EMERGENCY_ACCESS_STATUS_INVITED,
    1: EMERGENCY_ACCESS_STATUS_ACCEPTED,
    2: EMERGENCY_ACCESS_STATUS_CONFIRMED,
    3: EMERGENCY_ACCESS_STATUS_RECOVERY_INITIATED,
    4: EMERGENCY_ACCESS_STATUS_RECOVERY_APPROVED
}

MAP_EMERGENCY_STATUS_TO_INT = {
    EMERGENCY_ACCESS_STATUS_INVITED: 0,
    EMERGENCY_ACCESS_STATUS_ACCEPTED: 1,
    EMERGENCY_ACCESS_STATUS_CONFIRMED: 2,
    EMERGENCY_ACCESS_STATUS_RECOVERY_INITIATED: 3,
    EMERGENCY_ACCESS_STATUS_RECOVERY_APPROVED: 4
}


# ------------------------------ Emergency type ----------------------- #
EMERGENCY_ACCESS_TYPE_VIEW = "view"
EMERGENCY_ACCESS_TYPE_TAKEOVER = "takeover"

MAP_EMERGENCY_TYPE = {
    0: EMERGENCY_ACCESS_TYPE_VIEW,
    1: EMERGENCY_ACCESS_TYPE_TAKEOVER
}

MAP_EMERGENCY_TYPE_TO_INT = {
    EMERGENCY_ACCESS_TYPE_VIEW: 0,
    EMERGENCY_ACCESS_TYPE_TAKEOVER: 1
}
