E_MEMBER_ROLE_PRIMARY_ADMIN = "primary_admin"
E_MEMBER_ROLE_ADMIN = "admin"
E_MEMBER_ROLE_MEMBER = "member"

ENTERPRISE_LIST_ROLE = [E_MEMBER_ROLE_PRIMARY_ADMIN, E_MEMBER_ROLE_ADMIN, E_MEMBER_ROLE_MEMBER]


E_MEMBER_STATUS_INVITED = "invited"
E_MEMBER_STATUS_CONFIRMED = "confirmed"
