POLICY_TYPE_PASSWORD_REQUIREMENT = "password_requirement"
POLICY_TYPE_MASTER_PASSWORD_REQUIREMENT = "master_password_requirement"
POLICY_TYPE_BLOCK_FAILED_LOGIN = "block_failed_login"
POLICY_TYPE_PASSWORDLESS = "passwordless"
POLICY_TYPE_2FA = '2fa'


LIST_POLICY_TYPE = [
    POLICY_TYPE_PASSWORD_REQUIREMENT,  POLICY_TYPE_MASTER_PASSWORD_REQUIREMENT,
    POLICY_TYPE_BLOCK_FAILED_LOGIN, POLICY_TYPE_PASSWORDLESS,
    POLICY_TYPE_2FA
]
