TOKEN_PREFIX = "cs."
TOKEN_TYPE_AUTHENTICATION = "authentication_locker"
TOKEN_TYPE_INVITE_MEMBER = "invite_member"
TOKEN_TYPE_TRIAL_ENTERPRISE = "trial_enterprise"

TOKEN_EXPIRED_TIME_INVITE_MEMBER = 24
TOKEN_EXPIRED_TIME_TRIAL_ENTERPRISE = 20 * 60       # 20 minutes
