NOTIFY_CHANGE_MASTER_PASSWORD = "change_master_password"
NOTIFY_LOGIN_NEW_DEVICE = "login_new_device"
NOTIFY_SHARING = "item_sharing"
NOTIFY_EMERGENCY_ACCESS = "emergency_access"
NOTIFY_DATA_BREACH = "data_breach"
NOTIFY_PWD_TIP_TRICK = "password_tip_trick"
NOTIFY_MARKETING = "marketing"
NOTIFY_OTHER = "other"

LIST_NOTIFY_CATEGORIES = [
    NOTIFY_CHANGE_MASTER_PASSWORD, NOTIFY_LOGIN_NEW_DEVICE, NOTIFY_SHARING,
    NOTIFY_EMERGENCY_ACCESS, NOTIFY_DATA_BREACH, NOTIFY_PWD_TIP_TRICK, NOTIFY_MARKETING, NOTIFY_OTHER
]
