# Generated by Django 3.1.4 on 2022-11-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker_statistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatisticDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.FloatField()),
                ('completed_time', models.FloatField()),
                ('latest_user_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'lk_user_statistics_date',
            },
        ),
    ]
