# Generated by Django 3.1.4 on 2022-12-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker_statistic', '0002_userstatisticdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistic',
            name='cs_created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
