# Generated by Django 3.1.4 on 2022-12-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker_statistic', '0003_auto_20221201_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistic',
            name='country',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
