# Generated by Django 3.1.4 on 2022-12-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker_statistic', '0004_auto_20221201_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistic',
            name='utm_source',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
