# Generated by Django 3.2.16 on 2022-12-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker_statistic', '0005_auto_20221201_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistic',
            name='lk_last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
