# Generated by Django 3.2.16 on 2023-01-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker_statistic', '0006_userstatistic_lk_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistic',
            name='lk_referral_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='paid_platforms',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
