# Generated by Django 3.2.18 on 2023-03-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker_statistic', '0007_auto_20230103_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistic',
            name='num_api_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='num_citizen_id_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='num_crypto_account_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='num_database_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='num_driver_license_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='num_passport_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='num_server_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='num_social_security_number_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='num_wireless_router',
            field=models.IntegerField(default=0),
        ),
    ]
