# Generated by Django 3.2.18 on 2023-05-15 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locker_statistic', '0008_auto_20230330_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlanFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.IntegerField()),
                ('email', models.CharField(max_length=128, null=True)),
                ('root_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_root', to='locker_statistic.userstatistic')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='locker_statistic.userstatistic')),
            ],
            options={
                'db_table': 'lk_user_plan_family',
            },
        ),
    ]
