# Generated by Django 3.2.18 on 2023-05-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker_statistic', '0009_userplanfamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistic',
            name='personal_trial_mobile_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='personal_trial_web_applied',
            field=models.BooleanField(default=False),
        ),
    ]
