# Generated by Django 3.2.18 on 2023-06-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker_statistic', '0010_auto_20230516_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistic',
            name='first_payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
