# Generated by Django 3.1.4 on 2021-09-29 05:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cs_member_roles',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=128)),
                ('codename', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'cs_permissions',
                'unique_together': {('scope', 'codename')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='My Team', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('locked', models.BooleanField(default=False)),
                ('business_name', models.CharField(blank=True, default='', max_length=128)),
                ('key', models.CharField(max_length=512, null=True)),
                ('default_collection_name', models.CharField(max_length=512, null=True)),
                ('public_key', models.TextField(null=True)),
                ('private_key', models.TextField(null=True)),
            ],
            options={
                'db_table': 'cs_teams',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('creation_date', models.FloatField()),
                ('revision_date', models.FloatField(null=True)),
                ('activated', models.FloatField(default=False)),
                ('account_revision_date', models.FloatField(null=True)),
                ('master_password', models.CharField(max_length=300, null=True)),
                ('master_password_hint', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('master_password_score', models.FloatField(default=0)),
                ('security_stamp', models.CharField(max_length=50, null=True)),
                ('key', models.TextField(null=True)),
                ('public_key', models.TextField(null=True)),
                ('private_key', models.TextField(null=True)),
                ('kdf', models.IntegerField(default=0)),
                ('kdf_iterations', models.IntegerField(default=100000)),
                ('timeout', models.IntegerField(default=15)),
                ('timeout_action', models.CharField(default='lock', max_length=16)),
            ],
            options={
                'db_table': 'cs_users',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=300, null=True)),
                ('access_time', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('key', models.TextField(null=True)),
                ('reset_password_key', models.TextField(null=True)),
                ('status', models.CharField(default='confirmed', max_length=128)),
                ('email', models.CharField(max_length=128, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='cystack_models.memberrole')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='cystack_models.team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='cystack_models.user')),
            ],
            options={
                'db_table': 'cs_team_members',
                'unique_together': {('user', 'team', 'role')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('access_all', models.BooleanField(default=False)),
                ('external_id', models.CharField(max_length=300)),
                ('creation_date', models.FloatField()),
                ('revision_date', models.FloatField(null=True)),
                ('name', models.TextField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='cystack_models.team')),
            ],
            options={
                'db_table': 'cs_groups',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('creation_date', models.FloatField()),
                ('revision_date', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='cystack_models.user')),
            ],
            options={
                'db_table': 'cs_folders',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('creation_date', models.FloatField()),
                ('revision_date', models.FloatField(null=True)),
                ('external_id', models.CharField(max_length=300, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='cystack_models.team')),
            ],
            options={
                'db_table': 'cs_collections',
            },
        ),
        migrations.CreateModel(
            name='Cipher',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('creation_date', models.FloatField()),
                ('revision_date', models.FloatField()),
                ('deleted_date', models.FloatField()),
                ('reprompt', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('type', models.IntegerField()),
                ('data', models.TextField(blank=True, null=True)),
                ('favorites', models.TextField(blank=True, null=True)),
                ('folders', models.TextField(blank=True, default='', null=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciphers', to='cystack_models.team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciphers', to='cystack_models.user')),
            ],
            options={
                'db_table': 'cs_ciphers',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='cystack_models.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='cystack_models.memberrole')),
            ],
            options={
                'db_table': 'cs_role_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_members', to='cystack_models.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_members', to='cystack_models.teammember')),
            ],
            options={
                'db_table': 'cs_groups_members',
                'unique_together': {('group', 'member')},
            },
        ),
        migrations.CreateModel(
            name='CollectionMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_only', models.BooleanField(default=False)),
                ('hide_passwords', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections_members', to='cystack_models.collection')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections_members', to='cystack_models.teammember')),
            ],
            options={
                'db_table': 'cs_collections_members',
                'unique_together': {('collection', 'member')},
            },
        ),
        migrations.CreateModel(
            name='CollectionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_only', models.BooleanField(default=False)),
                ('hide_passwords', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections_groups', to='cystack_models.collection')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections_groups', to='cystack_models.group')),
            ],
            options={
                'db_table': 'cs_collections_groups',
                'unique_together': {('collection', 'group')},
            },
        ),
        migrations.CreateModel(
            name='CollectionCipher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections_ciphers', to='cystack_models.cipher')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections_ciphers', to='cystack_models.collection')),
            ],
            options={
                'db_table': 'cs_collections_ciphers',
                'unique_together': {('collection', 'cipher')},
            },
        ),
    ]
