# Generated by Django 3.1.1 on 2021-06-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cs_account_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_time', models.IntegerField()),
                ('default_payment_method', models.CharField(default='wallet', max_length=128)),
                ('bw_id', models.CharField(max_length=128, null=True)),
                ('bw_email', models.CharField(max_length=128, null=True)),
                ('bw_email_verified', models.BooleanField(default=False)),
                ('bw_public_key', models.CharField(max_length=512, null=True)),
                ('bw_master_pass_score', models.FloatField(default=0, null=True)),
                ('bw_timeout', models.IntegerField(default=15)),
                ('bw_timeout_action', models.CharField(default='lock', max_length=16)),
            ],
            options={
                'db_table': 'cs_users',
                'managed': False,
            },
        ),
    ]
