# Generated by Django 3.1.4 on 2021-09-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='creation_date',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='revision_date',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
