# Generated by Django 3.1.4 on 2021-09-30 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0002_auto_20210929_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserRefreshToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.FloatField()),
                ('refresh_token', models.CharField(max_length=255)),
                ('token_type', models.CharField(max_length=128)),
                ('scope', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=128)),
                ('device_name', models.CharField(max_length=128, null=True)),
                ('device_type', models.CharField(max_length=128, null=True)),
                ('device_identifier', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_refresh_tokens', to='cystack_models.user')),
            ],
            options={
                'db_table': 'cs_user_refresh_tokens',
            },
        ),
        migrations.CreateModel(
            name='UserAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('expired_time', models.FloatField()),
                ('grant_type', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('refresh_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='cystack_models.userrefreshtoken')),
            ],
            options={
                'db_table': 'cs_user_access_tokens',
            },
        ),
    ]
