# Generated by Django 3.1.4 on 2021-10-06 07:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0005_auto_20211006_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='internal_id',
            field=models.CharField(default=uuid.uuid4, max_length=64, null=True),
        ),
    ]
