# Generated by Django 3.1.4 on 2021-10-12 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0007_delete_cipherfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=128)),
                ('country_phone_code', models.CharField(default=None, max_length=10)),
            ],
            options={
                'db_table': 'cs_countries',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('organization', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('postal_code', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('last4', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('country', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='cystack_models.country')),
            ],
            options={
                'db_table': 'cs_customers',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_id', models.CharField(default=None, max_length=128, null=True)),
                ('created_time', models.FloatField()),
                ('total_price', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('status', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('transaction_type', models.CharField(default='Payment', max_length=128)),
                ('payment_method', models.CharField(max_length=64, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('stripe_invoice_id', models.CharField(max_length=128, null=True)),
                ('code', models.CharField(max_length=128, null=True)),
                ('bank_id', models.IntegerField(default=None, null=True)),
                ('scope', models.CharField(default='pwdmanager', max_length=255)),
                ('plan', models.CharField(max_length=255)),
                ('duration', models.CharField(default='monthly', max_length=16)),
                ('metadata', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cystack_models.customer')),
                ('promo_code', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cystack_models.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cystack_models.user')),
            ],
            options={
                'db_table': 'cs_payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('team_id', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='cystack_models.payment')),
            ],
            options={
                'db_table': 'cs_payment_items',
            },
        ),
    ]
