# Generated by Django 3.1.4 on 2021-10-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0008_country_customer_payment_paymentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='token_invitation',
            field=models.TextField(default=None, null=True),
        ),
    ]
