# Generated by Django 3.1.4 on 2021-10-16 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0009_teammember_token_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=16)),
                ('acting_user_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('cipher_id', models.CharField(max_length=128, null=True)),
                ('collection_id', models.CharField(max_length=128, null=True)),
                ('creation_date', models.FloatField()),
                ('device_type', models.IntegerField(null=True)),
                ('group_id', models.CharField(max_length=128, null=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('team_id', models.CharField(max_length=128, null=True)),
                ('team_member_id', models.CharField(max_length=128, null=True)),
                ('policy_id', models.CharField(max_length=128, null=True)),
                ('provider_id', models.CharField(max_length=128, null=True)),
                ('team_provider_id', models.CharField(max_length=128, null=True)),
                ('user_provider_id', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'cs_events',
            },
        ),
    ]
