# Generated by Django 3.1.4 on 2021-11-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0010_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='cipher',
            name='view_password',
            field=models.BooleanField(default=True),
        ),
    ]
