# Generated by Django 3.1.4 on 2021-11-17 04:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0011_cipher_view_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='policy', serialize=False, to='cystack_models.team')),
                ('min_password_length', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)])),
                ('max_password_length', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)])),
                ('password_composition', models.BooleanField(default=False)),
                ('failed_login_attempts', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('failed_login_duration', models.IntegerField(default=600, validators=[django.core.validators.MinValueValidator(1)])),
                ('failed_login_block_time', models.IntegerField(default=900, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'cs_policy',
            },
        ),
    ]
