# Generated by Django 3.1.4 on 2021-11-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0012_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_request_login',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_block_until',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_failed_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
