# Generated by Django 3.1.4 on 2021-11-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0013_auto_20211117_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='avoid_ambiguous_character',
            field=models.BinaryField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='require_digit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='require_lower_case',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='require_special_character',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='require_upper_case',
            field=models.BooleanField(default=False),
        ),
    ]
