# Generated by Django 3.1.4 on 2021-11-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0014_auto_20211124_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='avoid_ambiguous_character',
            field=models.BooleanField(default=False),
        ),
    ]
