# Generated by Django 3.1.4 on 2021-11-26 08:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0015_auto_20211125_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAccess',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('creation_date', models.IntegerField()),
                ('revision_date', models.IntegerField()),
                ('last_notification_date', models.IntegerField(null=True)),
                ('recovery_initiated_date', models.IntegerField(null=True)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('wait_time_days', models.PositiveSmallIntegerField(default=7)),
                ('key_encrypted', models.TextField(null=True)),
                ('email', models.CharField(max_length=128, null=True)),
                ('grantee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_grantees', to='cystack_models.user')),
                ('grantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_grantors', to='cystack_models.user')),
            ],
            options={
                'db_table': 'cs_emergency_access',
            },
        ),
    ]
