# Generated by Django 3.1.4 on 2021-11-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0016_emergencyaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cipher',
            name='view_password',
        ),
    ]
