# Generated by Django 3.1.4 on 2021-12-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0018_auto_20211129_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='block_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='failed_login_owner_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='ip_allow',
            field=models.TextField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='policy',
            name='ip_block',
            field=models.TextField(blank=True, default='', max_length=512),
        ),
    ]
