# Generated by Django 3.1.4 on 2021-12-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0019_auto_20211207_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activated_date',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.FloatField(null=True),
        ),
    ]
