# Generated by Django 3.1.4 on 2021-12-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0020_auto_20211222_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccesstoken',
            name='sso_token_id',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
