# Generated by Django 3.1.4 on 2021-12-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0022_device_deviceaccesstoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmplan',
            name='max_device',
        ),
        migrations.RemoveField(
            model_name='pmplan',
            name='max_device_type',
        ),
    ]
