# Generated by Django 3.1.4 on 2021-12-27 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0024_auto_20211224_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='cipher',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_ciphers', to='cystack_models.user'),
        ),
    ]
