# Generated by Django 3.1.4 on 2021-12-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0025_cipher_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmplan',
            name='personal_share',
            field=models.BooleanField(default=False),
        ),
    ]
