# Generated by Django 3.1.4 on 2021-12-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0026_pmplan_personal_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='personal_share',
            field=models.BooleanField(default=False),
        ),
    ]
