# Generated by Django 3.1.4 on 2021-12-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0027_team_personal_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='hide_passwords',
            field=models.BooleanField(default=False),
        ),
    ]
