# Generated by Django 3.1.4 on 2021-12-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0028_teammember_hide_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='fcm_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
