# Generated by Django 3.1.4 on 2021-12-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0029_device_fcm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_login',
            field=models.FloatField(null=True),
        ),
    ]
