# Generated by Django 3.1.4 on 2021-12-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0030_device_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmplan',
            name='is_family_plan',
            field=models.BooleanField(default=False),
        ),
    ]
