# Generated by Django 3.1.4 on 2022-01-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0031_pmplan_is_family_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMUserPlanFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.IntegerField()),
                ('email', models.CharField(max_length=128, null=True)),
                ('root_user_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_plan_family', to='cystack_models.pmuserplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_plan_family', to='cystack_models.user')),
            ],
            options={
                'db_table': 'cs_pm_user_plan_family',
            },
        ),
    ]
