# Generated by Django 3.1.4 on 2022-01-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0032_pmuserplanfamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmuserplan',
            name='personal_trial_applied',
            field=models.BooleanField(default=False),
        ),
    ]
