# Generated by Django 3.1.4 on 2022-01-10 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0033_pmuserplan_personal_trial_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmuserplanfamily',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_plan_family', to='cystack_models.user'),
        ),
    ]
