# Generated by Django 3.1.4 on 2022-01-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0034_auto_20220110_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='browser',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='os',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
