# Generated by Django 3.1.4 on 2022-03-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0036_auto_20220110_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmuserplan',
            name='pm_mobile_subscription',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='pmuserplan',
            index=models.Index(fields=['pm_mobile_subscription'], name='cs_pm_user__pm_mobi_f3e434_idx'),
        ),
    ]
