# Generated by Django 3.1.4 on 2022-03-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0037_auto_20220303_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mobile_invoice_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
