# Generated by Django 3.1.4 on 2022-05-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0040_auto_20220310_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmuserplan',
            name='extra_time',
            field=models.IntegerField(default=0),
        ),
    ]
