# Generated by Django 3.1.4 on 2022-07-04 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0043_auto_20220629_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.FloatField()),
                ('updated_time', models.FloatField(null=True)),
                ('domain', models.CharField(max_length=128)),
                ('root_domain', models.CharField(max_length=128)),
                ('verification', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='cystack_models.team')),
            ],
            options={
                'db_table': 'cs_domains',
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'cs_ownership',
            },
        ),
        migrations.CreateModel(
            name='DomainOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('verification', models.BooleanField(default=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_ownership', to='cystack_models.domain')),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_ownership', to='cystack_models.ownership')),
            ],
            options={
                'db_table': 'cs_domain_ownership',
                'unique_together': {('domain', 'ownership')},
            },
        ),
    ]
