# Generated by Django 3.1.4 on 2022-07-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0044_domain_domainownership_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.FloatField()),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('company', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('country', models.CharField(default=None, max_length=128, null=True)),
            ],
            options={
                'db_table': 'cs_affiliate_submissions',
            },
        ),
    ]
