# Generated by Django 3.1.4 on 2022-07-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0045_affiliatesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatesubmission',
            name='status',
            field=models.CharField(default='submitted', max_length=64),
        ),
    ]
