# Generated by Django 3.1.4 on 2022-07-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0046_affiliatesubmission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedRelayAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_hash', models.CharField(db_index=True, max_length=64)),
                ('num_forwarded', models.PositiveIntegerField(default=0)),
                ('num_blocked', models.PositiveIntegerField(default=0)),
                ('num_replied', models.PositiveIntegerField(default=0)),
                ('num_spam', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'cs_deleted_relay_addresses',
            },
        ),
        migrations.CreateModel(
            name='RelayDomain',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cs_relay_domains',
            },
        ),
        migrations.CreateModel(
            name='RelayAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=64)),
                ('created_time', models.FloatField()),
                ('updated_time', models.FloatField(null=True)),
                ('num_forwarded', models.PositiveIntegerField(default=0)),
                ('num_blocked', models.PositiveIntegerField(default=0)),
                ('num_replied', models.PositiveIntegerField(default=0)),
                ('num_spam', models.PositiveIntegerField(default=0)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relay_addresses', to='cystack_models.relaydomain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relay_addresses', to='cystack_models.user')),
            ],
            options={
                'db_table': 'cs_relay_addresses',
            },
        ),
    ]
