# Generated by Django 3.1.4 on 2022-07-06 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0047_deletedrelayaddress_relayaddress_relaydomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('notification', models.BooleanField(default=True)),
                ('mail', models.BooleanField(default=True)),
                ('order_number', models.IntegerField()),
            ],
            options={
                'db_table': 'cs_notification_categories',
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.BooleanField(default=True)),
                ('mail', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='cystack_models.notificationcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='cystack_models.user')),
            ],
            options={
                'db_table': 'cs_notification_settings',
                'unique_together': {('user', 'category')},
            },
        ),
    ]
