# Generated by Django 3.1.4 on 2022-07-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0048_notificationcategory_notificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcategory',
            name='name_vi',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
