# Generated by Django 3.1.4 on 2022-07-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0049_notificationcategory_name_vi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmuserplan',
            name='extra_plan',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
