# Generated by Django 3.1.4 on 2022-07-21 02:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0051_auto_20220721_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Enterprise', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('creation_date', models.FloatField()),
                ('revision_date', models.FloatField(null=True)),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'e_enterprises',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseGroup',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('creation_date', models.FloatField()),
                ('revision_date', models.FloatField(null=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='cystack_models.enterprise')),
            ],
            options={
                'db_table': 'e_enterprise_groups',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseMemberRole',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'e_member_roles',
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'e_ownership',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseMember',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('access_time', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(default='confirmed', max_length=128)),
                ('email', models.CharField(max_length=128, null=True)),
                ('token_invitation', models.TextField(default=None, null=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_members', to='cystack_models.enterprise')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_members', to='cystack_models.enterprisememberrole')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_members', to='cystack_models.user')),
            ],
            options={
                'db_table': 'e_members',
                'unique_together': {('user', 'enterprise', 'role')},
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.FloatField()),
                ('updated_time', models.FloatField(null=True)),
                ('domain', models.CharField(max_length=128)),
                ('root_domain', models.CharField(max_length=128)),
                ('verification', models.BooleanField(default=False)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='cystack_models.enterprise')),
            ],
            options={
                'db_table': 'e_domains',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_members', to='cystack_models.enterprisegroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_members', to='cystack_models.enterprisemember')),
            ],
            options={
                'db_table': 'e_groups_members',
                'unique_together': {('group', 'member')},
            },
        ),
        migrations.CreateModel(
            name='DomainOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('verification', models.BooleanField(default=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_ownership', to='cystack_models.domain')),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_ownership', to='cystack_models.ownership')),
            ],
            options={
                'db_table': 'e_domain_ownership',
                'unique_together': {('domain', 'ownership')},
            },
        ),
    ]
