# Generated by Django 3.1.4 on 2022-07-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0054_customer_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='auto_approve',
            field=models.BooleanField(default=False),
        ),
    ]
