# Generated by Django 3.1.4 on 2022-08-02 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0055_domain_auto_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisemember',
            name='domain',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_members', to='cystack_models.domain'),
        ),
    ]
