# Generated by Django 3.1.4 on 2022-08-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0056_enterprisemember_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(db_index=True, max_length=255)),
                ('encrypted_metadata', models.TextField()),
                ('created_at', models.FloatField()),
            ],
            options={
                'db_table': 'cs_reply',
            },
        ),
    ]
