# Generated by Django 3.1.4 on 2022-08-04 08:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0057_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterprisePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('policy_type', models.CharField(max_length=128)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='cystack_models.enterprise')),
            ],
            options={
                'db_table': 'e_policy',
                'unique_together': {('enterprise', 'policy_type')},
            },
        ),
        migrations.CreateModel(
            name='PolicyFailedLogin',
            fields=[
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='policy_failed_login', serialize=False, to='cystack_models.enterprisepolicy')),
                ('failed_login_attempts', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('failed_login_duration', models.IntegerField(default=600, validators=[django.core.validators.MinValueValidator(1)])),
                ('failed_login_block_time', models.IntegerField(default=900, validators=[django.core.validators.MinValueValidator(1)])),
                ('failed_login_owner_email', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'e_policy_failed_login',
            },
        ),
        migrations.CreateModel(
            name='PolicyMasterPassword',
            fields=[
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='policy_master_password_requirement', serialize=False, to='cystack_models.enterprisepolicy')),
                ('min_length', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)])),
                ('require_lower_case', models.BooleanField(default=False)),
                ('require_upper_case', models.BooleanField(default=False)),
                ('require_special_character', models.BooleanField(default=False)),
                ('require_digit', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'e_policy_master_password',
            },
        ),
        migrations.CreateModel(
            name='PolicyPassword',
            fields=[
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='policy_password_requirement', serialize=False, to='cystack_models.enterprisepolicy')),
                ('min_length', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)])),
                ('require_lower_case', models.BooleanField(default=False)),
                ('require_upper_case', models.BooleanField(default=False)),
                ('require_special_character', models.BooleanField(default=False)),
                ('require_digit', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'e_policy_password',
            },
        ),
        migrations.CreateModel(
            name='PolicyPasswordless',
            fields=[
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='policy_passwordless', serialize=False, to='cystack_models.enterprisepolicy')),
                ('only_allow_passwordless', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'e_policy_passwordless',
            },
        ),
    ]
