# Generated by Django 3.1.4 on 2022-08-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0059_enterprisemember_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_leaked',
            field=models.BooleanField(default=False),
        ),
    ]
