# Generated by Django 3.1.4 on 2022-08-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0060_user_is_leaked'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='metadata',
            field=models.TextField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
