# Generated by Django 3.1.4 on 2022-08-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0063_pmplan_relay_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_relay_subdomain',
            field=models.BooleanField(default=False),
        ),
    ]
