# Generated by Django 3.1.4 on 2022-08-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0064_user_use_relay_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='enterprise_address',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='enterprise_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='enterprise_phone',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
