# Generated by Django 3.1.4 on 2022-08-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0066_payment_enterprise_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='enterprise_address',
            new_name='enterprise_country',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='enterprise_address1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='enterprise_address2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='enterprise_postal_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
