# Generated by Django 3.1.4 on 2022-09-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0068_relayaddress_block_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmuserplan',
            name='member_billing_updated_time',
            field=models.FloatField(default=None, null=True),
        ),
    ]
