# Generated by Django 3.1.4 on 2022-09-13 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0069_pmuserplan_member_billing_updated_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseBillingContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.FloatField()),
                ('email', models.EmailField(max_length=128)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_contacts', to='cystack_models.enterprise')),
            ],
            options={
                'db_table': 'e_billing_contacts',
                'unique_together': {('enterprise', 'email')},
            },
        ),
    ]
