# Generated by Django 3.1.4 on 2022-09-14 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0070_enterprisebillingcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisegroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enterprise_groups', to='cystack_models.user'),
        ),
    ]
