# Generated by Django 3.1.4 on 2022-09-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0071_enterprisegroup_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fd_credential_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fd_random',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(default='password', max_length=32),
        ),
    ]
