# Generated by Django 3.1.4 on 2022-10-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0072_auto_20220929_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_notify_failed',
            field=models.BooleanField(default=False),
        ),
    ]
