# Generated by Django 3.1.4 on 2022-10-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0074_pmuserplan_enterprise_trial_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='init_seats',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='init_seats_expired_time',
            field=models.FloatField(default=None, null=True),
        ),
    ]
