# Generated by Django 3.1.4 on 2022-11-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0075_auto_20221025_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_process',
            field=models.TextField(blank=True, default={'enterprise_onboarding': [], 'vault_to_dashboard': False}, max_length=512),
        ),
    ]
