# Generated by Django 3.1.4 on 2022-11-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0076_user_onboarding_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmuserplan',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
