# Generated by Django 3.1.4 on 2022-11-14 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0077_pmuserplan_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.AddField(
            model_name='group',
            name='enterprise_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharing_groups', to='cystack_models.enterprisegroup'),
        ),
        migrations.AddField(
            model_name='group',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='access_all',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='CollectionGroup',
        ),
    ]
