# Generated by Django 3.1.4 on 2022-11-14 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0078_auto_20221114_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='read_only',
        ),
        migrations.AddField(
            model_name='group',
            name='role',
            field=models.ForeignKey(default='member', on_delete=django.db.models.deletion.CASCADE, related_name='sharing_groups', to='cystack_models.memberrole'),
        ),
    ]
