# Generated by Django 3.1.4 on 2022-11-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0080_auto_20221114_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_added_by_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('team', 'enterprise_group')},
        ),
    ]
