# Generated by Django 3.1.4 on 2022-11-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0081_auto_20221114_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delete_account_date',
            field=models.FloatField(null=True),
        ),
    ]
