# Generated by Django 3.1.4 on 2022-11-21 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0082_user_delete_account_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy2FA',
            fields=[
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='policy_2fa', serialize=False, to='cystack_models.enterprisepolicy')),
                ('only_admin', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'e_policy_2fa',
            },
        ),
    ]
