# Generated by Django 3.1.4 on 2022-12-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0084_auto_20221130_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='onboarding_process',
            field=models.TextField(blank=True, default={'enterprise_onboarding': [], 'enterprise_onboarding_skip': False, 'tutorial': False, 'vault_to_dashboard': False, 'welcome': False}, max_length=512),
        ),
    ]
