# Generated by Django 3.1.4 on 2022-12-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0085_auto_20221202_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisemember',
            name='status',
            field=models.CharField(default='confirmed', max_length=128),
        ),
    ]
