# Generated by Django 3.2.16 on 2023-03-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0087_auto_20221220_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='is_saas_code',
            field=models.BooleanField(default=False),
        ),
    ]
