# Generated by Django 3.2.18 on 2023-03-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0089_user_saas_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timeout',
            field=models.IntegerField(default=20160),
        ),
    ]
