# Generated by Django 3.2.18 on 2023-03-20 05:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0090_alter_user_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickShare',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('access_id', models.CharField(max_length=128, unique=True)),
                ('creation_date', models.FloatField()),
                ('revision_date', models.FloatField()),
                ('deleted_date', models.FloatField(null=True)),
                ('type', models.IntegerField()),
                ('data', models.TextField(blank=True, null=True)),
                ('key', models.TextField(null=True)),
                ('password', models.CharField(max_length=512, null=True)),
                ('max_access_count', models.PositiveIntegerField(null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('expired_date', models.FloatField(null=True)),
                ('disabled', models.FloatField(default=False)),
                ('is_public', models.FloatField(default=True)),
                ('require_otp', models.FloatField(default=True)),
                ('cipher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_shares', to='cystack_models.cipher')),
            ],
            options={
                'db_table': 'cs_quick_shares',
            },
        ),
        migrations.CreateModel(
            name='QuickShareEmail',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('creation_date', models.FloatField()),
                ('email', models.EmailField(max_length=255)),
                ('code', models.CharField(max_length=32, null=True)),
                ('code_expired_time', models.FloatField(null=True)),
                ('quick_share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_share_emails', to='cystack_models.quickshare')),
            ],
            options={
                'db_table': 'cs_quick_share_emails',
                'unique_together': {('quick_share', 'email')},
            },
        ),
    ]
