# Generated by Django 3.2.18 on 2023-03-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0091_quickshare_quickshareemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickshare',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
