# Generated by Django 3.2.18 on 2023-03-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0092_alter_quickshare_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickshareemail',
            name='access_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quickshareemail',
            name='max_access_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
