# Generated by Django 3.2.18 on 2023-03-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0093_auto_20230320_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickshare',
            name='each_email_access_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
