# Generated by Django 3.2.18 on 2023-03-24 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0095_alter_quickshare_require_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quickshare',
            old_name='expired_date',
            new_name='expiration_date',
        ),
    ]
