# Generated by Django 3.2.18 on 2023-04-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0096_rename_expired_date_quickshare_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.IntegerField()),
                ('major', models.CharField(max_length=16)),
                ('minor', models.CharField(max_length=16)),
                ('patch', models.CharField(blank=True, default='', max_length=16)),
                ('build_number', models.CharField(blank=True, default='', max_length=16)),
                ('description_en', models.CharField(blank=True, default='', max_length=512)),
                ('description_vi', models.CharField(blank=True, default='', max_length=512)),
                ('client_id', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'cs_releases',
            },
        ),
    ]
