# Generated by Django 3.2.18 on 2023-04-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0097_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='environment',
            field=models.CharField(default='prod', max_length=128),
        ),
    ]
