# Generated by Django 3.2.18 on 2023-05-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0099_mission_userrewardmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
