# Generated by Django 3.2.18 on 2023-05-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0100_mission_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='reward_type',
            field=models.CharField(default='promo_code', max_length=64),
        ),
        migrations.AddField(
            model_name='mission',
            name='reward_value',
            field=models.FloatField(default=0),
        ),
    ]
