# Generated by Django 3.2.18 on 2023-05-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0101_auto_20230505_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='onboarding_process',
            field=models.TextField(blank=True, default={'enterprise_onboarding': [], 'enterprise_onboarding_skip': False, 'tutorial': False, 'tutorial_process': [], 'vault_to_dashboard': False, 'welcome': False}, max_length=512),
        ),
    ]
