# Generated by Django 3.2.18 on 2023-05-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0102_alter_user_onboarding_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmuserplan',
            name='personal_trial_mobile_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pmuserplan',
            name='personal_trial_web_applied',
            field=models.BooleanField(default=False),
        ),
    ]
