# Generated by Django 3.2.18 on 2023-05-18 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0103_auto_20230515_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='only_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='only_promo_codes', to='cystack_models.user'),
        ),
    ]
