# Generated by Django 3.2.18 on 2023-05-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0104_promocode_only_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrewardmission',
            name='answer',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
