# Generated by Django 3.2.18 on 2023-06-13 04:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0107_auto_20230602_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludeDomain',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('created_time', models.FloatField()),
                ('domain', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclude_domains', to='cystack_models.user')),
            ],
            options={
                'db_table': 'cs_exclude_domains',
                'unique_together': {('user', 'domain')},
            },
        ),
    ]
