# Generated by Django 3.2.20 on 2023-08-29 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0108_excludedomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.FloatField()),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('university', models.CharField(blank=True, max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(max_length=255)),
                ('promo_code', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_emails', to='cystack_models.user')),
            ],
            options={
                'db_table': 'cs_education_email',
                'unique_together': {('user', 'email')},
            },
        ),
    ]
