# Generated by Django 3.2.20 on 2023-08-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0109_educationemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationemail',
            name='education_type',
            field=models.CharField(default='student', max_length=64),
        ),
    ]
