# Generated by Django 3.2.20 on 2023-09-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0110_educationemail_education_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_time'], name='cs_payments_created_85461a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='cs_payments_status_48c09f_idx'),
        ),
    ]
