# Generated by Django 3.2.20 on 2023-09-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0111_auto_20230911_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationemail',
            name='verification_token',
            field=models.CharField(max_length=512),
        ),
    ]
