# Generated by Django 3.2.20 on 2023-09-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystack_models', '0113_alter_educationemail_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='only_plan',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
